# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Southeast Conservation Adaptation Strategy (SECAS)
webmaster: roy_hewitt@fws.gov
description: > # this means to ignore newlines until "baseurl:"
  Through the Southeast Conservation Adaptation Strategy (SECAS), diverse
  partners are working together to design and achieve a connected network of
  landscapes and seascapes that supports thriving fish and wildlife populations
  and improved quality of life for people across the southeastern United States
  andthe Caribbean.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.secassoutheast.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
  - node_modules
  - _src/js
